# .github/workflows/ci-devsecops.yml
name: CI/CD DevSecOps Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings --cov=src --cov-report=xml

      - name: Audit dependencies
        run: |
          pip-audit

      - name: Build Docker image
        run: |
          docker build -t ds-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner on image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ds-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  # Job pour le déploiement (dry-run)
  deploy-dry-run:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.2' # Utilisez une version récente de kubectl

      - name: Dry-run Kubernetes deployment
        run: |
          kubectl apply -f k8s/ --dry-run=client -o yaml
